#!/usr/bin/env bash
#MISE description="Delete the SAM stack"
set -euo pipefail

echo "Deleting base infrastructure stack: ${STACK_NAME}"
mise x -- sam delete --stack-name "${STACK_NAME}" --no-prompts
