#!/usr/bin/env bash
#MISE description="Deploy SAM stack"
#MISE depends=["build"]
set -euo pipefail

mise x -- sam deploy \
  --stack-name "${STACK_NAME}" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
  --resolve-s3 \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset
